const errors = {
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    PASSWORD_NOT_MATCH: 'PASSWORD_NOT_MATCH',
    QUESTION_NOT_FOUND: 'QUESTION_NOT_FOUND',
    QUESTION_BAD_FORMATTED: 'QUESTION_BAD_FORMATTED',
    ANSWER_BAD_FORMATTED: 'ANSWER_BAD_FORMATTED'
}

export default errors;